### ISSUE TITLE
Can you export activity over a certain time range?

### ISSUE THREAD

**Issue by sffc** [karlicoss/ghexport#2]
Thanks for building this!

Say I want to export my activity only for the last 7 days.  Is there an option to do this in `ghexport`?

**Comment by karlicoss** [comment]
Hi! Not at the moment, wondering why do you need this?

Note that, due to API limitations, Github already [only returns last 90 days, and no more than 300 events](https://github.com/karlicoss/ghexport#api-limitations) of data... So if you're worried about receiving too much data, you are very unlikely to the way it is. For example, my single export is only 10 Mb (uncompressed).

**Comment by sffc** [comment]
Thanks for the reply!  I'm mainly interested in exporting my contribution activity over a certain period of time to help summarize what I've done (e.g., for reports to my team/manager).  I realized that I can mostly achieve this using only the "get_activity" endpoint.  I threw this together to start at solving my problem:

https://github.com/sffc/gh_activity_summarizer
